core:
    navigation:
        setting:
            label: Setting
            icon: wrench
            children:
                general:
                    label: General
                    route: dt_system_setting_general
                theme:
                    label: Theme
                    route: dt_system_setting_theme
        system:
            label: System
            icon: gears
            children:
                log:
                    label: Log
                    route: dt_system_log
                cache:
                    label: Cache
                    route: dt_system_cache
