imports:
    - { resource: assets/assets.yml }
    - { resource: "@FileBundle/Resources/config/system/navigation.yml" }
    - { resource: "@PageBundle/Resources/config/system/navigation.yml" }
    - { resource: "@UserBundle/Resources/config/system/navigation.yml" }
    - { resource: "@CoreBundle/Resources/config/navigation.yml" }
